#!/usr/bin/perl
#
# check-pending -- utility (to be run from cron) to check for pending host
#                  changes in Sauron database
#
# $Id$
#

$SAURONHOME = "/opt/sauron";
$MAILCOMMAND = "/bin/mail -s 'Sauron: pending host changes' nobody@localhost";
$MAXLINES = 100;

######################################################################

$server = shift;

unless ($server) {
    print "syntax: $0 <servername>\n\n";
    exit(1);
}


open(PIPE,"$SAURONHOME/status --quiet --pending=$server |") 
    || die("status command pipe failed");

while(<PIPE>) {
    next if /^\s*$/;
    push @output, $_;
    last if (@output > $MAXLINES);
}
close(PIPE);

if (@output > 1) {
    open(PIPE,"| $MAILCOMMAND") || die("mail pipe failed");
    foreach $line (@output) {
	print PIPE $line;
    }
    print PIPE "\n\n";
    close(PIPE);
}

exit 0

# eof

