#!/bin/sh
#
# sauron-backup   -- script to backup sauron database daily (from cron)
#
# $Id$
#

BACKUPCMD="pg_dump -h localhost sauron"
BACKUPDIR=/opt/sauron/backups
WEEKLYBACKUPDAY=0    # make weekly backup on sundays

########################################################################

WEEKDAY=`date +%w`
DATESTR=`date +%Y%m%d`


if [ ! -d ${BACKUPDIR} ]; then
    echo "$0: cannot access backup directory: $BACKUPDIR"
    exit 1;
fi


# make weekly backup...
if [ "$WEEKDAY" == "$WEEKLYBACKUPDAY" ]; then
    ${BACKUPCMD} | gzip -c9 > ${BACKUPDIR}/sauron-weekly-${DATESTR}.gz
fi

# make daily backup...
${BACKUPCMD} | gzip -c9 > ${BACKUPDIR}/sauron-daily-${WEEKDAY}.gz


# eof

