#!/usr/bin/perl -I/usr/local/sauron
#
# addgroup - utility to create users
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2000,2002.
# $Id$
#
require 5;
use Getopt::Long;
use Term::ReadKey;
use Sauron::DB;
use Sauron::Util;

my ($PG_DIR,$PG_NAME) = ($0 =~ /^(.*\/)(.*)$/);
$0 = $PG_NAME;

if (-r "/etc/sauron/config") {
  $config_file="/etc/sauron/config";
} elsif (-r "/usr/local/etc/sauron/config") {
  $config_file="/usr/local/etc/sauron/config"; 
} else {
  die("cannot find config file in /etc/sauron or /usr/local/etc/sauron");
}

do "$config_file" || die("cannot load config: $config_file");

$cdate = time;
$user = (getpwuid($<))[0];

##############################################

$result = GetOptions("help|h","name=s","group=s");

if ($opt_help) {
  print "syntax: $0 [--help] [--group=name] [--name=\"<groupname>\"]\n";
  exit(0);
}

db_connect($DB_CONNECT);


unless ($opt_group) {
  print "Enter group name: ";
  $opt_group = lc(ReadLine 0);
  chomp $opt_group;
  $i=1;
}
fatal("Invalid groupname '$opt_group'!") 
  unless ($opt_group =~ /^[a-z0-9_\-]+$/);


unless ($opt_name) {
  print "Enter group description: ";
  $opt_name = ReadLine 0;
  chomp $opt_name;
  $i=1;
}

$user = (getpwuid($<))[0];

if ($i) { # ask confirmation only in interactive session...
  print "\t Groupname: $opt_group\n",
  "\t Description: $opt_name\n",
  "Add this group [y/n]?";

  $t=ReadLine 0;
  chomp $t;
  unless ($t eq 'y' || $t eq 'Y') {
    print "Group not added!\n";
    exit(1);
  }
}


$res=db_exec("INSERT INTO user_groups " .
	     "(name,comment) VALUES('$opt_group','$opt_name');");

fatal("Cannot add group! (group already exists?)\n" .  db_errormsg()) 
	  if ($res < 0);

print "Group $opt_group added succesfully.\n";


exit;


# eof :-)

