#!/usr/bin/perl
#
# adduser - utility to create users
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2000.
# $Id$
#
require 5;
use Getopt::Long;
use Term::ReadKey;

my ($PG_DIR,$PG_NAME) = ($0 =~ /^(.*\/)(.*)$/);
$0 = $PG_NAME;

if (-r "/etc/sauron/config") {
  $config_file="/etc/sauron/config";
} elsif (-r "/usr/local/etc/sauron/config") {
  $config_file="/usr/local/etc/sauron/config"; 
} else {
  die("cannot find config file in /etc/sauron or /usr/local/etc/sauron");
}

do "$config_file" || die("cannot load config: $config_file");
do "$PG_DIR/util.pl";
do "$PG_DIR/db.pl";


$cdate = time;
$user = (getpwuid($<))[0];

sub fatal($) {
  my ($msg) = @_;
  print STDERR "$0: $msg\n";
  exit(1);
}

##############################################

my(
   $result,$superuser,$user,$salt,$pwd,
   $i,$t,$r,$res
  );

$result = GetOptions("user=s","superuser","help|h","passwd=s","name=s",
		     "group=s","comment=s","email=s");

if ($opt_help) {
  print "syntax: $0 [--user=username] [--group=name] [--superuser] " .
        "[--help]\n" ,
        "\t\t[--passwd=password] [--name=\"<user's full name>\"]\n",
	"\t\t[--email=\"foo\@bar\"] [--comment=\"comments\"]\n\n";
  exit(0);
}

db_connect();


unless ($opt_user) {
  print "Enter username: ";
  $opt_user = ReadLine 0;
  chomp $opt_user;
  $i=1;
}
fatal("Invalid username '$opt_user'!") unless ($opt_user =~ /^\S+$/);

unless ($opt_group) {
  print "Enter group name (empty for none): ";
  $opt_group = ReadLine 0;
  chomp $opt_group;
  $i=1;
}

if ($opt_group) {
  undef @q;
  db_query("SELECT id FROM user_groups WHERE name='$opt_group';",\@q);
  fatal("Cannot find group '$opt_group'") unless (@q > 0);
  $gid=$q[0][0];
} else {
  $gid=-1;
}


unless ($opt_name) {
  print "Enter user description (full name): ";
  $opt_name = ReadLine 0;
  chomp $opt_name;
  $i=1;
}

unless ($opt_email) {
  print "Enter user email address: ";
  $opt_email = ReadLine 0;
  chomp $opt_email;
  $i=1;
}

unless ($opt_comment) {
  print "Enter optional user info: ";
  $opt_comment = ReadLine 0;
  chomp $opt_comment;
  $i=1;
}

unless ($opt_passwd) {
  print "Enter password: ";
  ReadMode 'noecho';
  $opt_passwd = ReadLine 0;
  print "\n";
  ReadMode 'normal';
  chomp $opt_passwd;
  $i=1;
}

$superuser=($opt_superuser==1?"true":"false");
$user = (getpwuid($<))[0];
$salt=int(rand(900000)+100000);
$pwd=pwd_crypt($opt_passwd,$salt);

if ($i) { # ask confirmation only in interactive session...
  print "\t Username: $opt_user\n",
  "\t Longname: $opt_name\n",
  "\t    email: $opt_email\n",
  "\t  comment: $opt_comment\n",
  "\tsuperuser: $superuser\n",
  "Add this user [y/n]?";

  $t=ReadLine 0;
  chomp $t;
  unless ($t eq 'y' || $t eq 'Y') {
    print "User not added!\n";
    exit(1);
  }
}

$res=db_exec("INSERT INTO users " .
     "(username,password,name,superuser,muser,cuser,cdate,gid,comment," .
     " email) " .
     "VALUES('$opt_user','$pwd','$opt_name',$superuser," .
     " '$user','$user',$cdate,$gid,'$opt_comment','$opt_email');");

fatal("Cannot add user to users table! (user already exists?)\n" . 
      db_errormsg()) if ($res < 0);

print "User $opt_user added succesfully.\n";
print "Remember to give user some rights with moduser command.\n"
	  if ($superuser ne 'true');
exit;

