#!/usr/bin/perl -I/usr/local/sauron
#
# deluser - utility to delete users
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2000-2002.
# $Id$
#
require 5;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::BackEnd;

my ($PG_DIR,$PG_NAME) = ($0 =~ /^(.*\/)(.*)$/);
$0 = $PG_NAME;

if (-r "/etc/sauron/config") {
  $config_file="/etc/sauron/config";
} elsif (-r "/usr/local/etc/sauron/config") {
  $config_file="/usr/local/etc/sauron/config"; 
} else {
  die("cannot find config file in /etc/sauron or /usr/local/etc/sauron");
}

do "$config_file" || die("cannot load config: $config_file");

##############################################

my(
   $opt_help,$opt_user,
   $result,$id,$res,
   $i,$t,@q
   );

$result = GetOptions("user=s","help|h");

if ($opt_help) {
  print "syntax: $0 [--help] [--user=<username>]\n";
  exit(0);
}

db_connect($DB_CONNECT);


unless ($opt_user) {
  print "Enter user to be deleted: ";
  chomp($opt_user = <STDIN>);
  $i=1;
}
fatal("Invalid username '$opt_user'!") unless ($opt_user =~ /^\S+$/);



fatal("Cannot find user '$opt_user' from users table!")
	  if (get_user($opt_user,\%user) < 0);
$id=$user{id};

if ($i) { # ask confirmation only in interactive session...
  print "\t Username: $opt_user (id=$id)\n",
        "\t Longname: $user{name}\n",
        "\tsuperuser: " . ($user{superuser} eq 't' ? 'Yes' : 'No') ."\n",
	"\t    email; $user{email}\n",
        "\t  comment: $user{comment}\n";

  print "Delete this user [y/n]?";
  chomp ($t=<STDIN>);
  unless ($t eq 'y' || $t eq 'Y') {
    print "User not deleted!\n";
    exit(1);
  }
}

fatal("Cannot delete user from users table!") if (delete_user($id) < 0);


print "User $opt_user deleted succesfully.\n";
exit(0);

# eof
