#!/usr/bin/perl -I/usr/local/sauron
#
# export-by-group  ... searches hosts by group
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2004.
# Modifications Riku Meskanen <mesrik@iki.fi> 2005,2015
# $Id:$
#
require 5;
use Getopt::Long;
use Time::Local;
use Sauron::DB;
use Sauron::Util;
use Sauron::BackEnd;
use Sauron::Sauron;
use strict;

load_config();

my $user = (getpwuid($<))[0];
my $host = `hostname`;
$host =~ s/\n//g;

my $opt_help = 0;
my $opt_all = 0;
my $opt_verbose = 0;
my $opt_csv = 0;

GetOptions("help|h","any|a","csv|c","verbose|v");

if ($opt_help || @ARGV < 1) {
    print "syntax: $0 [--help] <servername> domain-regex group-regex\n",
    "\t--any\t\tincludes any host type\n",
    "\t--csv\t\tCSV output\n",
    "\t--verbose\tmore verbose output\n";
  print "\n" if ($opt_help);
  exit(0);
}

my $servername = shift;
my $domainre   = shift || '.';
my $groupre    = shift || '.';

my $sql = "SELECT a.ip,h.domain,z.name,g.name,g2.name " .
    "FROM a_entries a JOIN  hosts h ON h.id=a.host " .
    "JOIN zones z ON z.id=h.zone " .
    "LEFT JOIN group_entries ge ON h.id=ge.host " .
    "LEFT JOIN groups g on g.id=ge.grp " .
    "LEFT JOIN groups g2 on g2.id=h.grp " .
    "WHERE z.name ~ " . db_encode_str($domainre) . " AND " .
    "(g.name ~ " . db_encode_str($groupre) . " OR " .
    "g2.name ~ " . db_encode_str($groupre) . ") " .
    ($opt_all ? "" : " AND h.type = ANY (ARRAY[1,4,7]) ") .
    "ORDER BY z.name,h.domain;";
db_connect();

my $serverid=get_server_id($servername);
fatal("cannot find server '$servername'") unless ($serverid > 0);

print "# server: $servername\n# date: ".localtime(time())." by $user\n"
    if ($opt_verbose);
print "# sql: " . $sql . "\n\n"
    if ($opt_verbose);

my @reply;
db_query($sql,\@reply);

for my $i (0..$#reply) {
  my ($ip,$domain,$zone,$group,$maingroup) = @{$reply[$i]};
  $group=$maingroup if ($maingroup =~ /$groupre/);
  if ($opt_csv) {
      printf "\"%s\",\"%s.%s\",\"%s\"\n",$ip,$domain,$zone,$group;
  } else {
      printf "%s %s.%s %s\n",$ip,$domain,$zone,$group;
  }
}


exit 0;

#################################

# eof
