#!/usr/bin/perl -I/usr/local/sauron
#
# import-roots  imports root servers from named.roots (named.ca) file.
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2001.
# $Id$
#
require 5;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::UtilZone;
use Sauron::BackEnd;

my ($PG_DIR,$PG_NAME) = ($0 =~ /^(.*\/)(.*)$/);
$0 = $PG_NAME;

if (-r "/etc/sauron/config") {
  $config_file="/etc/sauron/config";
} elsif (-r "/usr/local/etc/sauron/config") {
  $config_file="/usr/local/etc/sauron/config"; 
} else {
  die("cannot find config file in /etc/sauron or /usr/local/etc/sauron");
}

do "$config_file" || die("cannot load config: $config_file");

###################################################################

GetOptions("help|h","update|u");

if ($opt_help || @ARGV < 2) {
  print "syntax: $0 [--help] [--update] <servername | default> <named.root>\n";
  exit(0);
}

$servername=$ARGV[0];
$file=$ARGV[1];

fatal("cannot read input file '$file'") unless (-r $file);

fatal("DB_CONNECT not defined in configuration!") unless ($DB_CONNECT);
db_connect($DB_CONNECT);

if ($servername eq 'default') {
  print "Creating default root servers\n";
  $serverid=-1;
} else {
  $serverid=get_server_id($servername);
  fatal("cannot find server '$servername'") if ($serverid < 0);
  print "Creating root servers for server: $servername (id=$serverid)\n";
}

process_zonefile($file,".",\%zonedata,0);
$count = keys %zonedata;

print "Found $count records...\n";

db_begin();

$acount=0;
$ncount=0;

unless ($opt_update) {
  $res=db_exec("DELETE FROM root_servers WHERE server=$serverid;");
  fatal("cannot delete old root server records") if ($res < 0);
}

foreach $host (keys %zonedata) {
  $rec=$zonedata{$host};
  print "host: $host $rec->{TTL}\n";
  $ttl=$rec->{TTL};
  $ttl=3600000 unless ($ttl > 0);

  if (@{$rec->{A}}) {
    #print "A: " . join(",",@{$rec->{A}}) . "\n";
    for $i (0..$#{$rec->{A}}) {
      $ip=$rec->{A}[$i];
      db_exec("INSERT INTO root_servers (server,ttl,domain,type,value) " .
	      " VALUES($serverid,$ttl,'$host','A','$ip');");
      die("cannot insert A record") if ($res < 0);
      $acount++;
    }
  }
  if (@{$rec->{NS}}) {
    #print "NS: " . join(",",@{$rec->{NS}}) . "\n";
    for $i (0..$#{$rec->{NS}}) {
      $ns=$rec->{NS}[$i];
      db_exec("INSERT INTO root_servers (server,ttl,domain,type,value) " .
	      " VALUES($serverid,$ttl,'$host','NS','$ns');");
      die("cannot insert NS record") if ($res < 0);
      $ncount++;
    }
  }
}


if ($acount < 1) {
  print STDERR "No A records found, insert failed!\n";
  exit(1);
}

if ($ncount < 1) {
  print STDERR "No NS records found, insert failed!\n";
  exit(1);
}

die("commit failed") if (db_commit() < 0);

print "$acount root server A records inserted\n";
print "$ncount root server NS records inserted\n";

exit 0;

# eof

