#!/usr/bin/perl -I/opt/sauron
#
# import-zone-comments - imports DNS comments from zone file 
# Copyright (c) Michal Švamberg <svamberg@cesnet.cz> 2025.
# $Id:$
#
# Imports only comments listed after the record. 
# Does not import comments in the SOA block.

require 5;
# use Net::Netmask;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::UtilZone;
use Sauron::BackEnd;
use Sauron::Sauron;
use Sauron::SetupIO;
use Parse::RecDescent;
use Encode qw( encode is_utf8 decode );

use Data::Dumper; # debug


use strict;
use warnings;

#$::RD_TRACE  = 1; # debug 
#$::RD_HINT   = 1; # debug 

set_encoding();
load_config();

my ($servername, $serverid, $zoneid, $zonename, $zonefile, $user, $zonedata);

sub load_zone_file($$);
sub comment_soa($);
sub compress_zone($);
sub import_comments($$$);

my $opt_help    = 0;
my $opt_verbose = 0;
my $opt_noop    = 0;

GetOptions(
    'help|h'    => \$opt_help,
    'verbose|v' => \$opt_verbose,
    'noop|n'    => \$opt_noop,
) or die "Chyba při parsování parametrů!\n";

if ($opt_help || @ARGV < 2) {
    print "syntax: $0 [options] <servername> <zone> [<zone file>]\n";
    print "options:\n",
       "\t--verbose\t\tdisplay more detailed progress reports\n",
       "\t--noop\t\trun without changes in database\n".
       "\t--help\t\t\tdisplay this help\n\n";
    print "" if ($opt_help);
    exit(1);
}

$servername = shift;
$zonename = shift;
$zonefile = shift;
$user = (getpwuid($<))[0];


fatal("cannot read zone file: $zonefile") if ( $zonefile && ! -r $zonefile);

set_muser($user);
db_connect();

$serverid=get_server_id($servername);
fatal("cannot find server: $servername") unless ($serverid > 0);

fatal("invalid zone name: $zonename") unless (valid_domainname($zonename));
$zonename =~ s/\.$//;
#$origin = $zonename . '.';

$zoneid=get_zone_id($zonename,$serverid);
fatal("cannot find zone: $zonename on $servername") unless ($zoneid > 0);


fatal("import of 'reverse' zones not supported")
    if ($zonename =~ /\.(ip6|in-addr)\.arpa\.?$/);

# -------
# Grammar
# -------

my $grammar = <<'GRAMMAR';
# ------------------------------------------------------------
#   DNS zone file – grammar for Parse::RecDescent
# ------------------------------------------------------------
# <skip> a <autotree> **musí** být na první řádce!
<skip: qr/[ \t]*/>          # only spaces and tabs, NOT \r or \n
<autotree: 1>               # vracíme reference, ne kopie
{
    # Globální proměnné, které parser používá během zpracování
    my $zone        = { records => [] };
    my $prev_owner  = '';
    my $origin      = '';        # poslední $ORIGIN (pro @)

    sub _push { push @{ $zone->{records} }, $_[0] }
}
# ---------------------------  START  -----------------------
file:   line(s)               { $return = $zone }
# ---------------------------  LINES  -----------------------
line:   blank_line
    |   empty_line
    |   comment_line
    |   directive_line
    |   rr_line
    { $return = $item[1] }
# ------------------------------------------------------------
#  Prázdný řádek (pouze bílé znaky nebo koncový znak)
# ------------------------------------------------------------
blank_line:
        ws(?) eol               { _push({ type=>'blank', line_nr => $thisline }); $return = undef }

empty_line: 
        /^\s*(?:\r?\n|$)/  { $return = { type=>'empty', raw=>$item[1], line_nr => $thisline }; }

# ---------------------------  COMMENT -----------------------
comment_line:
        comment ws(?) eol      {
            my $txt = $item[1];
            $txt =~ s/^\s*;//;          # odebereme úvodní ;
            $txt =~ s/\s+$//;           # a koncové mezery
            _push({ type=>'comment', text=>$txt, line_nr => $thisline });
            $return = $item[1];
        }

comment:    /;[^\n]*/    { 
            $return = $item[1] ; 
            $return =~ s/^;// ; # odebereme uvodni ;
            $return =~ s/^\s*//; # odebereme uvodni mezery
            $return =~ s/\s*$//; # odebereme koncove mezery 
        }

# ---------------------------  DIRECTIVE --------------------
directive_line:
        directive ws(?) eol           { $return = $item[1] }

directive:
        origin_directive
    |   ttl_directive

origin_directive:
        /\$ORIGIN/ domain'.' comment(?) {
            $origin = $item[2]->{name} . '.';
            my $rec = {
                type      => 'directive',
                directive => 'ORIGIN',
                value     => $origin,
                comment   => $item[3] ? $item[3] : undef,
                line_nr   => $thisline,
            };
            _push($rec);
            $return = $rec;
        }

ttl_directive:
        /\$TTL/ number comment(?) {
            my $rec = {
                type      => 'directive',
                directive => 'TTL',
                value     => $item[2],
                comment   => $item[3] ? $item[3] : undef,
                line_nr   => $thisline,
            };
            _push($rec);
            $return = $rec;
        }

# ---------------------------  RESOURCE RECORD -------------
rr_line:
        rr ws(?) eol                { $return = $item[1] }

rr:
        owner(?) ttl(?) class(?) type rdata ws(?) comment(?) {
            # Pokud není explicitní owner, použijeme předchozí
            my $owner = $item[1][0];
            $owner = $prev_owner unless $owner;
            $prev_owner = $owner if $owner;

            my $rec = {
                type    => 'rr',
                owner   => $owner,
                ttl     => $item[2][0],
                class   => $item[3][0] ? $item[3][0] : 'IN',
                rtype   => $item[4],
                rdata   => $item[5],
                comment => $item[7][0] ? $item[7][0] : undef,
                line_nr => $thisline,
            };
            _push($rec);
            $return = $rec;
        }
     | <error>

# ---------------------------  TOKENS -----------------------
owner:
        ownername ...type_exists  {
            my $val = $item[1];
            # seznam povolených tříd – stejný jako CLASS
            my %classes = map { $_ => 1 } qw( IN CH HS );
            if ( $classes{$val} ) {
                # třída byla zadána místo owneru -> odmítneme
                $::RD_HINT && warn "owner '$val' looks like a CLASS – rejected\n";
                # vrátíme undef a tím "reject"
                $return = undef;
                # (alternativně můžete $parser->reject; nebo die)
            }
            else {
                $return = $val;
            }
        }
    |   '@'                          { $return = $origin }   


ttl:        number              { $return = $item[1] }

# ---------------------------  RDATA -----------------------
rdata:
        mx_rdata
    |   srv_rdata
    |   naptr_rdata
    |   caa_rdata
    |   txt_rdata
    |   generic_rdata       { $return = $item[1] }

# ---- MX ----------------------------------------------------
mx_rdata:
        'MX' ws number ws name {
            $return = { pref=>$item[3], exchange=>$item[5] };
        }

# ---- SRV ---------------------------------------------------
srv_rdata:
        'SRV' ws number ws number ws number ws name {
            $return = {
                priority => $item[3],
                weight   => $item[5],
                port     => $item[7],
                target   => $item[9],
            };
        }

# ---- NAPTR -------------------------------------------------
naptr_rdata:
        'NAPTR' ws number ws number ws quoted_string ws quoted_string ws quoted_string ws name {
            $return = {
                order       => $item[3],
                pref        => $item[5],
                flags       => $item[7],
                service     => $item[9],
                regexp      => $item[11],
                replacement => $item[13],
            };
        }

# ---- CAA ---------------------------------------------------
caa_rdata:
        'CAA' ws number ws caa_tag ws quoted_string {
            $return = {
                flags => $item[3],
                tag   => $item[5],
                value => $item[7],
            };
        }

caa_tag:    /issue|issuewild|iodef|issuemail/

# ---- TXT ---------------------------------------------------
txt_rdata:
        'TXT' ws quoted_string(s?) {
            $return = join('', @{$item[3]});
        }

# ---- generic (A, AAAA, CNAME, …) ---------------------------
generic_rdata:
        token_until_comment_or_newline   { $return = $item[1] }

# ---------------------------  HELPERS -----------------------
name:       /[A-Za-z0-9\-_]+(?:\.[A-Za-z0-9\-_]+)*/   { $return = $item[1] }
ownername:  name'.'     { $return = $item[1] }
      |     '*.'name    { $return = $item[1] }
      |     '*.'name'.' { $return = $item[1] }
      |     name        { $return = $item[1] }

domain:     name

number:     /\d+/                                   { $return = $item[1] }

class:      /IN|CH|HS/                              { $return = $item[1] }

type:       /(A|AAAA|NS|CNAME|SOA|MX|TXT|SRV|NAPTR|CAA|PTR|SPF|SSHFP|TLSA|DS|DNSKEY|RRSIG|NSEC|NSEC3|NSEC3PARAM)[\s\n]/ { $return = $item[1]; $return =~ s/\s+$// }
type_exists:       /.*(A|AAAA|NS|CNAME|SOA|MX|TXT|SRV|NAPTR|CAA|PTR|SPF|SSHFP|TLSA|DS|DNSKEY|RRSIG|NSEC|NSEC3|NSEC3PARAM)\s+/ 
                                                    { $return = $item[1] }

quoted_string:
        /"([^"\\]|\\.)*"/ {
            my $s = $item[1];
            $s =~ s/^"//; $s =~ s/"$//;
            $s =~ s/\\([\\"])/$1/g;               # od‑escapování \" a \\
            $return = $s;
        }


ws:         /[ \t]+/

eol:        /\r?\n/

# token_until_comment_or_newline – vše až do ; nebo konce řádku,
#   zachováme ale i počáteční mezery (budou oříznuty níže)
token_until_comment_or_newline:
        # 1. buď celý uvozovkový řetězec (může obsahovat ;), 
        # 2. nebo libovolný znak, který není středník
        /(?:"([^"\\]|\\.)*"|[^;\n])+/ {
            my $t = $item[1];
            $t =~ s/^\s+//;      # odstraňte úvodní mezery
            $t =~ s/\s+$//;      # a koncové mezery
            $return = $t;
        }

GRAMMAR

# -------------------------------------------------------------
#  Funkce – načte a parsuje zónový soubor
# -------------------------------------------------------------
sub load_zone_file($$) {
    my ($path, $ast) = @_;

    my $parser = Parse::RecDescent->new($grammar)
        or die "Nelze vytvořit parser (pravděpodobně chyba v gramatice)";

    open my $fh, '<:encoding(UTF-8)', $path
        or die encode('UTF-8',"Nelze otevřít $path: $!");

    local $/ = undef;
    my $text = <$fh>;
    close $fh;
    
    # NEPOTREBUJEME SOA ZAZNAM
    comment_soa(\$text);

    # konvert from multi-line to one-line format
    compress_zone(\$text);

    # odstranění BOM (pokud existuje)
    $text =~ s/^\x{FEFF}//;

    # ujistíme se, že $text je interně UTF‑8
    $text = decode('UTF-8',$text) unless is_utf8($text);
    #print Dumper($text);

    $. = 0;                            # reset čítače řádků
    $$ast = $parser->file($text);
    unless ($ast) {
        my $msg = sprintf "Parse error in %s (at line %d )", $path, $.;
        die $msg;
    }
}


# ------------------------------------------------------------
# compress_dns_zone( $ref_to_zone )
#
#  $ref_to_zone – reference na řetězec, který obsahuje celý
#                 obsah DNS zónového souboru (může mít
#                 konce řádků \n nebo \r\n).
#
#  Funkce najde všechny záznamy, které jsou rozděleny do
#  více řádků pomocí kulatých závorek ‘( … )’ a přetvoří je
#  na jediný řádek.  Počet fyzických řádků, které byl
#  odstraněn, je uveden jako komentář „; converted from X
#  lines to 1 line“.
#
#  Funkce mění řetězec *in‑place* a zároveň ho vrací.
# ------------------------------------------------------------
sub compress_zone($) {
    my ($zone_ref) = @_;
    
    # Původní obsah rozdělíme na řádky (podporujeme i \r\n)
    my @orig = split /\r?\n/, ${$zone_ref};
            
    my @out;               # výstupní řádky
    my @buffer;            # řádky aktuálního multiline‑bloku
    my $line_cnt = 0;      # počet řádků v bufferu
    my $inside   = 0;      # jsme uvnitř ( ... ) ?
            
    foreach my $raw (@orig) {
        # Odstraníme koncové mezery – komentáře necháme,
        # protože mohou být na konci řádku za závorkou.
        my $line = $raw;
    
        # Pokud právě nejsme v blocích a řádek neobsahuje '(' → normální řádek
        if ( !$inside ) {
            if ( $line =~ /\(/ && $line !~ /\)/ ) {
                # začátek multiline záznamu ( '(' bez odpovídající ')')
                $inside   = 1;
                @buffer   = ($line);
                $line_cnt = 1;    
                next;
            }
            else {
                push @out, $line;
                next;
            }
        }

        # ----- uvnitř multiline bloku -----
        push @buffer, $line;
        $line_cnt++;

        # Konec bloku?
        if ( $line =~ /\)/ ) {
            # -------------------------------------------------
            # Sestavíme jeden řádek
            # -------------------------------------------------
            my $joined = join ' ', @buffer;               # spojíme s mezerou
            $joined =~ s/\s*\(\s*/ /;                       # odstraníme '('
            $joined =~ s/\s*\)\s*/ /;                       # odstraníme ')'

            my $total = () = $joined =~ /"/g;             # spocitat vsechny uvozovky
            my $i = 0;
            $joined =~ s/"/ ++$i == 1 || $i == $total ? '"' : '' /eg; # odstraneni vnitrnich uvozovek

            $joined =~ s/\s+/ /g;                          # zmenšíme mezery
            $joined =~ s/^\s+|\s+$//g;                     # ořízneme konce

            # Přidáme informativní komentář (tolik radku, kolik bylo zkraceni
            if ($line_cnt > 0) {
                $joined .= "\n; converted from multi-line" for 1 .. $line_cnt;
            }
            push @out, $joined;

            # Reset směru – připravíme se na další záznam
            $inside   = 0;
            @buffer   = ();
            $line_cnt = 0;
        }
        # pokud není ještě konec, jen pokračujeme ve sbírání
    }

    # Pokud soubor končí uvnitř neuzavřeného bloku, necháme jej tak,
    # ale přidáme obsah bufferu beze změny (nedetekováno jako
    # správný multiline).
    if ($inside) {
        push @out, @buffer;
    }

    # Spojíme řádky zpět do jediného řetězce (originální zakončení \n)
    ${$zone_ref} = join "\n", @out;
}

#=====================================================================
# comment_soa( $ref_to_string )
#
#   $ref_to_string – reference na celý obsah zónového souboru
#
#   Funkce projde řádky, najde všechna možná zápisy SOA a před
#   každým řádkem SOA‑bloku přidá středník (ponechá původní odsazení).
#   Pracuje přímo na referenci, takže se neprovádí zbytečné kopírování
#   velkých řetězců.
#
#   Návratová hodnota – reference na (stejný) řetězec s úpravou.
#=====================================================================
sub comment_soa($) {
    my ($r_txt) = @_;                     # reference na vstupní text
    my @lines = split /\n/, $$r_txt;      # pracujeme po řádcích

    my $in_soa       = 0;                  # jsme uvnitř blokového SOA?
    my $paren_depth  = 0;                  # hloubka závorek u blokového SOA

    for my $i (0 .. $#lines) {
        my $line = $lines[$i];

        # ------------------------------
        # 1) Řádky, které už jsou komentované, necháme beze změny
        # ------------------------------
        if ( $line =~ /^\s*;/ ) {
            next;
        }

        # ------------------------------
        # 2) Pokud ještě nejsme v SOA‑bloku a řádek obsahuje slovo SOA
        # ------------------------------
        unless ($in_soa) {
            if ( $line =~ /\bSOA\b/i ) {

                # zakomentovat tento řádek (zachovat odsazení)
                $line =~ s/^(\s*)/$1;/;
                $lines[$i] = $line;

                # Zjistíme, jestli SOA začíná blokem v závorkách
                if ( $line =~ /\(/ && $line !~ /\)/ ) {
                    $in_soa       = 1;
                    $paren_depth = 1;          # první '(' nalezen
                }
                next;                           # další řádek už bude zpracován v kroku 3
            }
        }

        # ------------------------------
        # 3) Jsme uvnitř blokového SOA → každé řádky zakomentovat
        # ------------------------------
        if ($in_soa) {
            $line =~ s/^(\s*)/$1;/;
            $lines[$i] = $line;

            # aktualizace hloubky závorek (aby funkce zvládla i
            # případ, kdy jsou v SOA další '(' a ')')
            $paren_depth++ while $line =~ /\(/g;
            $paren_depth-- while $line =~ /\)/g;

            # když se vrátíme na nulu, blok skončil
            $in_soa = 0 if $paren_depth <= 0;
            next;
        }

        # ------------------------------
        # 4) Ostatní řádky – ponecháme beze změny
        # ------------------------------
        $lines[$i] = $line;
    }

    # Sestavíme řetězec zpět (ponecháme původní konce řádků)
    $$r_txt = join "\n", @lines;
}

# ---------------
# import_comments
# ---------------
sub import_comments($$$) {
  my ($data, $server, $zone) = shift @_;
  my ($rec, $res, $ret, $sql, $comment, $blcomment);

  #print "$data\n";
  #print "$$data->{records}\n";

  $blcomment='';
  for my $i (0 .. $#{$$data->{records}}) {
    $rec = $$data->{records}->[$i];

    next if $$rec{type} eq 'directive';

    if ($$rec{type} eq 'comment') {
      $blcomment = $blcomment ? "$blcomment; $$rec{text}" : $$rec{text};
      next;
    }
    if ($$rec{type} eq 'blank') {
      $blcomment = ''; # end of block
      next;    
    }
    
    next unless ($$rec{comment} or $blcomment); # blokovy ani radkovy komentar

    #print "$i: $$rec{type} $$rec{owner} -> $$rec{class} -> $$rec{rtype}\n"; 
    $comment = db_encode_str($$rec{comment} ? $$rec{comment} : $blcomment);
    
    if ($$rec{rtype} =~ /^(A|AAAA)$/ and $$rec{owner}) {
      $sql = qq{
          UPDATE hosts
             SET info = $comment
           WHERE zone   = '$zoneid'
             AND domain = '$$rec{owner}'
             AND type   = '1'
             AND (info IS NULL OR info = '')
      };
      print "db_exec: $sql\n" if $opt_verbose;
      db_exec($sql) unless $opt_noop;
    }
    elsif ($$rec{rtype} eq 'CNAME' and $$rec{owner}) {
      $sql = qq{
          UPDATE hosts
             SET info = $comment
           WHERE zone   = '$zoneid'
             AND domain = '$$rec{owner}'
             AND type   = '4'
             AND (info IS NULL OR info = '')
      };
      db_exec($sql) unless $opt_noop;
      print "db_exec: $sql\n" if $opt_verbose;
    }
    elsif ($$rec{rtype} eq 'TXT' and $$rec{owner} =~ /\w+\._domainkey/) {
      $sql = qq{
          UPDATE txt_entries
             SET comment = $comment
           WHERE type    = '12'
             AND ref     = '$zoneid'
             AND txt  like '$$rec{owner} %'
             AND (comment IS NULL OR comment = '')
      };
      db_exec($sql) unless $opt_noop;
      print "db_exec: $sql\n" if $opt_verbose;
    }
    elsif ($$rec{rtype} eq 'SSHFP' and $$rec{owner}) {
      my ($sshfp_alg, $sshfp_ht, $sshfp_fp) = split /\s+/, $$rec{rdata};
      my $host_id = get_host_id($zoneid, $$rec{owner});
      $sql = qq{
        UPDATE sshfp_entries
           SET comment     = $comment
         WHERE ref         = '$host_id'
           AND algorithm   = '$sshfp_alg'
           AND hashtype    = '$sshfp_ht'
           AND fingerprint = '$sshfp_fp'
           AND (comment IS NULL OR comment = '')
      };
      db_exec($sql) unless $opt_noop;
      print "db_exec: $sql\n" if $opt_verbose;
    }
    elsif ($$rec{rtype} eq 'DS' and $$rec{owner}) {
      my ($ds_key_tag,$ds_algorithm,$ds_digest_type,$ds_digest) = split /\s+/, $$rec{rdata};
      my $host_id = get_host_id($zoneid, $$rec{owner});
      $sql = qq{
        UPDATE ds_entries
           SET comment     = $comment
         WHERE ref         = '$host_id'
           AND key_tag     = '$ds_key_tag'
           AND algorithm   = '$ds_algorithm'
           AND digest_type = '$ds_digest_type'
           AND digest      = '$ds_digest'
           AND (comment IS NULL OR comment = '')
      };
      db_exec($sql) unless $opt_noop;
      print "db_exec: $sql\n" if $opt_verbose;
    }
    elsif ($$rec{rtype} eq 'SRV' and $$rec{owner}) {
      my ($srv_priority, $srv_weight, $srv_port, $srv_target) = split /\s+/, $$rec{rdata};
      my $host_id = get_host_id($zoneid, $$rec{owner});
      $sql = qq{
        UPDATE srv_entries
           SET comment = $comment
         WHERE ref     = '$host_id'
           AND type    = '1'
           AND pri     = '$srv_priority'
           AND weight  = '$srv_weight'
           AND port    = '$srv_port'
           AND target  = '$srv_target'
           AND (comment IS NULL OR comment = '')
      };
      db_exec($sql) unless $opt_noop;
      print "db_exec: $sql\n" if $opt_verbose;
    }
    # tabulka hosts: delegation (2), MX (3), glue (6), SRV (8)
    # tabulka zoneentries, ...
    else {
      print "unknown record $i: $$rec{owner} $$rec{class} $$rec{rtype} $$rec{rdata}\n";
    }
  }

  return 0;
}


# --------------------
# Main code - continue
# --------------------

load_zone_file($zonefile, \$zonedata);

#print Dumper($zonedata);
print "Number of loaded records: $#{$$zonedata{records}}\n";


import_comments(\$zonedata,$serverid,$zonename);


print "All done.\n";
exit(0);



# eof

