#!/usr/bin/perl -I/usr/local/sauron
#
# import-ethers  imports Ethernet card manufacturer codes&descriptions
#                from text file (Ethernet.txt)
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2000-2003.
# $Id$
#
require 5;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::Sauron;

load_config();

###################################################################

my(
   $file,$c,
   $code,$info,%ethers,$icount,$ea,$res,$ucount
  );

GetOptions("help|h","force|f");

if ($opt_help || @ARGV < 1) {
  print "syntax: $0 [--help] [--force] <Ethernet.txt>\n\n";
  print "" if ($opt_help);
  exit(0);
}

$opt_force = ($opt_force ? 1 : 0);
$file=shift;

fatal("cannot read input file '$file'") unless (-r $file);
fatal("DB_CONNECT not defined in configuration!") unless ($DB_CONNECT);

db_connect($DB_CONNECT);
#db_debug(1);


open(FILE,"$file") || fatal("cannot open input file '$file'");
while (<FILE>) {
  next unless /^\s*([0-9A-F]{6})\s+(\S.*)$/ or
              /^([0-9A-F]{2}-[0-9A-F]{2}-[0-9A-F]{2})\s+\(hex\)\s+(\S.*)$/;
  $code=$1; 
  $info=$2;
  next if ($info =~ /^\(base/);
  $info =~ s/(\s+|\t+)/ /g;
  $info =~ s/\'/\\\'/g;
  $code =~ s/-//g;
  $ethers{$code}=$info;
  #print "$code:$info:\n";
}
close(FILE);

$c= keys %ethers;
print "Found descriptions for $c adapter manufacturers.\n";

fatal("Nothing to do.") if ($c < 1);


# insert codes to ether_info table
$icount=0;

foreach $ea (keys %ethers) {
  $info=$ethers{$ea};
  $res=db_exec("INSERT INTO ether_info (ea,info) " .
	       "VALUES('$ea','$info');");
  $icount++ unless ($res < 0);
  if (($res < 0) && $opt_force) {
    $res=db_exec("UPDATE ether_info SET info='$info' WHERE ea='$ea';");
    $ucount++ unless ($res < 0);
  }
}

print "$icount entries inserted in adapter info table\n";
print "$ucount entries updated in adapter info table\n" if ($ucount>0);

exit 0;

# eof

