#!/usr/bin/perl
#
# import-roots  imports root servers from named.roots (named.ca) file.
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2001.
# $Id$
#
require 5;
use Getopt::Long;

my ($PG_DIR,$PG_NAME) = ($0 =~ /^(.*\/)(.*)$/);
$0 = $PG_NAME;

do "$PG_DIR/config" || die("cannot load config");
do "$PG_DIR/util.pl";
do "$PG_DIR/db.pl";
do "$PG_DIR/util_zone.pl";

###################################################################

$result = GetOptions("help|h","update|u");

if ($opt_help || @ARGV < 2) {
  print "syntax: $0 [--help] [--update] <servername | default> <named.root>\n";
  exit(0);
}

$servername=$ARGV[0];
$file=$ARGV[1];

fatal("cannot read input file '$file'") unless (-r $file);

db_connect();

if ($servername eq 'default') {
  print "Creating default root servers\n";
  $serverid=-1;
} else {
  undef @q;
  db_query("SELECT id FROM servers WHERE name='$servername';",\@q);
  die("Cannot find server '$servername'") unless ($q[0][0] > 0);
  $serverid=$q[0][0];
  print "Creating root servers for server: $servername\n";
}

process_zonefile("fh0000",$file,".",\%zonedata,0);
$count = keys %zonedata;

print "Found $count records...\n";

db_begin();

$acount=0;
$ncount=0;

unless ($opt_update) {
  $res=db_exec("DELETE FROM root_servers WHERE server=$serverid;");
  die("cannot delete old root server records") if ($res < 0);
}

foreach $host (keys %zonedata) {
  $rec=$zonedata{$host};
  print "host: $host $rec->{TTL}\n";
  $ttl=$rec->{TTL};
  $ttl=3600000 unless ($ttl > 0);

  if (@{$rec->{A}}) {
    #print "A: " . join(",",@{$rec->{A}}) . "\n";
    for $i (0..$#{$rec->{A}}) {
      $ip=$rec->{A}[$i];
      db_exec("INSERT INTO root_servers (server,ttl,domain,type,value) " .
	      " VALUES($serverid,$ttl,'$host','A','$ip');");
      die("cannot insert A record") if ($res < 0);
      $acount++;
    }
  }
  if (@{$rec->{NS}}) {
    #print "NS: " . join(",",@{$rec->{NS}}) . "\n";
    for $i (0..$#{$rec->{NS}}) {
      $ns=$rec->{NS}[$i];
      db_exec("INSERT INTO root_servers (server,ttl,domain,type,value) " .
	      " VALUES($serverid,$ttl,'$host','NS','$ns');");
      die("cannot insert NS record") if ($res < 0);
      $ncount++;
    }
  }
}


if ($acount < 1) {
  print STDERR "No A records found, insert failed!\n";
  exit(1);
}

if ($ncount < 1) {
  print STDERR "No NS records found, insert failed!\n";
  exit(1);
}

die("commit failed") if (db_commit() < 0);

print "$acount root server A records inserted\n";
print "$ncount root server NS records inserted\n";

exit 0;

# eof

