#!/usr/bin/perl -I/usr/local/sauron
#
# keygen -- utility for creating TSIG/DNSSEC keys
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2005.
# $Id$
#
require 5;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::Sauron;
use Sauron::BackEnd;
use Digest::MD5;
use MIME::Base64;
use Sauron::SetupIO;
use open ':locale';

my %KEY_ALGORITHMS = (
		       0=>'reserved',
		       1=>'RSA/MD5',
		       2=>'DH',
		       3=>'DSA',
		       4=>'ECC',
		       157=>'HMAC-MD5',
		       158=>'HMAC-SHA1',
		       159=>'HMAC-SHA256',
		       160=>'HMAC-SHA384',
		       161=>'HMAC-SHA512'
		      );

# Map Sauron algorithm id <-> tsig-keygen algorithm name (lower case).
my %TSIG_ALG_NAME = (
		       157=>'hmac-md5',
		       158=>'hmac-sha1',
		       159=>'hmac-sha256',
		       160=>'hmac-sha384',
		       161=>'hmac-sha512'
		    );

# Default TSIG algorithm used when --algorithm is not given.
my $DEFAULT_TSIG_ALGORITHM = 'HMAC-SHA256';

set_encoding();
load_config();

GetOptions("help|h","setmasterkey:s","add:s","del:s","regen:s","list:s",
	   "verbose|v","algorithm=s");

# Resolve a TSIG algorithm name (any case, e.g. 'HMAC-SHA256') to its
# Sauron algorithm id, or 0 if the name is not supported.
sub tsig_algo_id($) {
    my($name) = @_;
    return 0 unless (defined $name && $name ne '');
    $name =~ tr/A-Z/a-z/;
    for my $id (keys %TSIG_ALG_NAME) {
	return $id if ($TSIG_ALG_NAME{$id} eq $name);
    }
    return 0;
}

if ($opt_help || not (defined($opt_add) || defined $opt_del || 
		   defined $opt_regen || defined $opt_list || 
		   defined $opt_setmasterkey) ) {
  print "syntax: $0 <server> [OPTIONS]\n",
        "interactive options:\n\n",
        "\t--setmasterkey\tset sauron master key\n",
        "\t--add\t\tadd a key\n",
        "\t--del\t\tdelete a key\n",
        "\t--regen\t\tregenerate (non-static) key(s)\n",
        "\t--list\t\tlist keys\n\n",
        "non-interactive options:\n\n",
        "\t--setmasterkey=\"<passphrase>\"\n",
        "\t--list=<server>\n",
        "\t--regen=<server>,<keytype>\n",
        "\t--del=<server>,<keyname>\n",
        "\t--add=\"<server>,<keyname>,<keytype>,<keylen>[,<comments>,<passphrase>]\"\n",
        "\t--algorithm=<alg>\tTSIG algorithm (default: $DEFAULT_TSIG_ALGORITHM)\n",
	"\n\t--verbose\tverbose output\n",
        "\n\nsupported key types: TSIG\n",
        "supported TSIG algorithms: HMAC-SHA256, HMAC-SHA384, HMAC-SHA512, HMAC-SHA1, HMAC-MD5\n\n";
  exit(0);
}

my $user = (getpwuid($<))[0];
set_muser($user);
umask 077;

db_connect();

# --setmasterkey

if (defined $opt_setmasterkey) { setmasterkey($opt_setmasterkey); }
elsif (defined $opt_add) { addkey($opt_add); }
elsif (defined $opt_del) { delkey($opt_del); }
elsif (defined $opt_list) { listkeys($opt_list); }
elsif (defined $opt_regen) { regenkeys($opt_regen); }
else { fatal("unknown option?"); }

exit;

##########################################################################


sub getserver($) {
    my($ans) = @_;
    my($ret);
    unless ($ans) {
	print "Server name: ";
	chomp($ans = <STDIN>);
    }
    $ret=get_server_id($ans);
    fatal("cannot find server: $ans") unless($ret > 0);
    return $ret;
}

sub getname($) {
    my($ans) = @_;
    unless ($ans) {
	print "Key name: ";
	chomp($ans = <STDIN>);
    }
    fatal("invalid key name: $ans") unless (valid_tsig_keyname($ans));
    return $ans;
}

sub gettype($) {
    my($ans) = @_;
    unless ($ans) {
	print "Key type [TSIG]: ";
	chomp($ans = <STDIN>);
	$ans = 'TSIG' unless ($ans);
    }

    fatal("invalid/unsupported key type: $ans")
	unless ($ans =~ /^(TSIG)$/);
    return $ans;
}

sub getlen($$$$) {
    my($ans,$min,$max,$def) = @_;
    unless ($ans ne '') {
	print "Key length ($min-$max) [$def]: ";
	chomp($ans = <STDIN>);
    }
    $ans=$def unless ($ans);
    fatal("key site out of range ($min-$max): $ans")
	unless ($ans >= $min && $ans <= $max);
    return $ans;
}

sub make_tmpdir() {
    my $ctx = Digest::MD5->new;
    my $prefix = '/tmp/sauron.';
    my $tmpdir;

    while ($tmpdir eq '') {
	$ctx->add($$);
	$ctx->add(rand(999999999));
	$tmpdir=$prefix.$ctx->hexdigest;
	$tmpdir='' if (-e $tmpdir);
    } 

    mkdir($tmpdir,0700) || 
	fatal("failed to create temporary directory: $tmpdir");
    return $tmpdir;
}


sub generate_key($$$$) {
    my($name,$type,$len,$algo) = @_;
    my $key;

    fatal("support this keytype not implemented yet: $type")
	unless ($type eq 'TSIG');

    my $alg_name = $TSIG_ALG_NAME{$algo};
    fatal("unsupported TSIG algorithm id: $algo") unless ($alg_name);

    # Modern BIND ships tsig-keygen for generating TSIG shared secrets;
    # dnssec-keygen no longer supports the HMAC algorithms.  The program
    # path can be overridden with the SAURON_TSIG_KEYGEN_PROG config option.
    my $tsig_prog = ($SAURON_TSIG_KEYGEN_PROG || '/usr/sbin/tsig-keygen');
    fatal("Cannot execute tsig-keygen: $tsig_prog")
	unless (-x $tsig_prog);

    # Use the list form of open() so the key name cannot be interpreted by
    # a shell (it is already validated by valid_tsig_keyname(), but be safe).
    open(PIPE,"-|",$tsig_prog,"-a",$alg_name,"--",$name) ||
	fatal("failed to run $tsig_prog");
    while(<PIPE>) {
	chomp;
	$key = $1 if (/secret\s+"([^"]+)"/);
    }
    close(PIPE);
    fatal("failed to generate key!") unless ($key);

    return $key;
}



sub setmasterkey($) {
    my($masterkey) = @_;
    my $keyfile=$CONFIG_FILE . ".key";
    my $oldkey;

    if (-f $keyfile) {
	my $fmode = (stat($keyfile))[2];
	fatal("existing keyfile with unsafe permissions: $keyfile")
	    if ($fmode & 0027);

	open(FILE,"$keyfile") || fatal("failed to open: $keyfile");
	while(<FILE>) {
	    $oldkey=$1 if (/^Key:\s+(\S+)\s*$/);
	}
	close(FILE);
	
	if ($oldkey) {
	    fatal("invalid (not Base64 encoded) masterkey in $keyfile")
		unless ($oldkey =~ /^[a-zA-Z0-9+\/=]+$/);
	    $oldkey=decode_base64($oldkey);

	    print 
		"WARNING! Backup database and config.key before attempting\n",
		"to change Sauron masterkey! Continue (N/y) ?";
	    my $cont = <STDIN>;
	    chomp($cont);
	    fatal("operation aborted") unless ($cont =~ /^[Yy]$/);
	}
    }

    unless ($masterkey) {
	print "Enter passphrase: ";
	chomp($masterkey=<STDIN>);
	fatal("Cannot use empty passphrase") unless ($masterkey);
    }
	
    my $ctx = Digest::MD5->new;
    $ctx->add($masterkey);
    $masterkey='';
    my $key = $ctx->digest;

    if ($oldkey) {
	# re-encrypt existing keys in database
	print "Re-encrypting existing keys in database...\n";
	my (@keys,$i);
	db_begin();
	if  (db_query("SELECT id,secretkey,name,algorithm " .
		      "FROM keys",\@keys) < 0) {
	    db_rollback();
	    fatal("failed to read existing keys from database");
	}
	for $i (0..$#keys) {
	    my $name = $keys[$i][2];
	    my $algo = $keys[$i][3];
	    # All TSIG family algorithms (HMAC-MD5/SHA1/SHA256/SHA384/SHA512).
	    fatal("unsupported key: $name (algorithm=$algo)")
	      if ($algo < 157 || $algo > 161);
	    if ($keys[$i][1]) {
		# Re-encrypt the stored (padded) ciphertext blocks: decrypt
		# with the old master key, encrypt with the new one.  Length 0
		# keeps the padding intact so the round-trip is exact.
		my $okey=tsig_secret_decrypt($oldkey,decode_base64($keys[$i][1]),0);
		my $nkey=encode_base64(tsig_secret_encrypt($key,$okey),"");
		chomp($nkey);
		if (db_exec("UPDATE keys SET secretkey='$nkey' " .
			    "WHERE id=$keys[$i][0]\n") < 0) {
		    db_rollback();
		    fatal("failed to update key id=$keys[$i][0]");
		}
		print "key: $name old: $keys[$i][1] new: $nkey\n"
		  if ($opt_verbose);
	    }
	}
    }

    unless (open(FILE,">$keyfile")) {
	db_rollback();
	fatal("cannot write to file: $keyfile");
    }
    print FILE "Key: ".encode_base64($key)."\n";
    close(FILE);
    fatal("failed to commit key updates to database!")
	if (db_commit() < 0);
    print "Sauron master key set.\n";
}



sub addkey() {
    my($add) = @_;
    my($algo,$mode);

    fatal("Sauron master key not defined/available " .
	  "(generate using --setmasterkey)") unless ($SAURON_KEY);

    my ($server,$name,$type,$len,$comment,$key) = split(/,/,$add);
    $server=getserver($server);
    $name=getname($name);
    $comment=~s/^\s+|\s+$//g;

    fatal("Key with same name allready exists: $name")
	if (get_key_by_name($server,$name) > 0);

    $type=gettype($type);
    if ($type eq  'TSIG') {
	my $alg = ($opt_algorithm || $DEFAULT_TSIG_ALGORITHM);
	$algo = tsig_algo_id($alg);
	fatal("unsupported TSIG algorithm: $alg\n" .
	      "supported: HMAC-SHA256, HMAC-SHA384, HMAC-SHA512, HMAC-SHA1, HMAC-MD5")
	    unless ($algo);
    } else {
	fatal("unsupported key type");
    }

    if ($key) {
	# Static key: the secret is supplied (Base64) by the user.  Store it
	# encrypted just like a generated key so it decrypts correctly when
	# the server configuration is generated.
	fatal("Key must be in Base64 (MIME) format")
	    unless ($key =~ /^[a-zA-Z0-9+\/=]+$/);
	my $raw = decode_base64($key);
	$len = length($raw) * 8;
	$key = encode_base64(tsig_secret_encrypt($SAURON_KEY,$raw),"");
	$mode=1;
    } else {
	print "Generating key...\n";
	my $okey = generate_key($name,$type,$len,$algo);
	my $raw = decode_base64($okey);
	# tsig-keygen determines the secret length from the algorithm; record
	# the actual length (in bits) so it can be trimmed back on decryption.
	$len = length($raw) * 8;
	$key = encode_base64(tsig_secret_encrypt($SAURON_KEY,$raw),"");
	print "Key: $okey  Encrypted-Key: $key\n" if ($opt_verbose);
	$mode=0;
    }

    chomp($key);
    fatal("failed to add key: $name")
	if (add_key({type=>1,ref=>$server,name=>$name,protocol=>2,mode=>$mode,
		     algorithm=>$algo,keysize=>$len,secretkey=>$key,
		     comment=>$comment}) < 1);
    
    print "Key added successfully.\n";
}

sub listkeys($) {
    my($args) = @_;
    my($i,@q,$typerule);

    my ($server,$type) = split(/,/,$args);
    $server=getserver($server);
    $type=gettype($type) unless ($type eq '' && $args ne '');
    if ($type > 0) {
	$typerule = " AND algorithm=$type ";
    }

    db_query("SELECT id,type,name,keytype,nametype,protocol,algorithm," .
	     " mode,keysize,publickey,secretkey,comment " .
	     "FROM keys " .
	     "WHERE type=1 AND ref=$server $typerule ORDER by name",\@q);
    if (@q < 1) {
	print "No keys found.\n";
	return;
    }
    print "Key name                  Type     Bits Mode   Comments\n";
    print "------------------------- -------- ---- ------ ------------------------------\n";
    for $i (0..$#q) {
	printf "%-25s %-8s %4d %-6s %-30s\n",$q[$i][2],
	                               $KEY_ALGORITHMS{$q[$i][6]},
	                               $q[$i][8],
	                               ($q[$i][7] == 0 ? 'Auto':'Static'),
	                               substr($q[$i][11],0,30);
	                               
    }
}


sub delkey($) {
    my($args) = @_;

    my ($server,$name) = split(/,/,$args);
    $server=getserver($server);
    $name=getname($name);

    my $id = get_key_by_name($server,$name);
    fatal("cannot find key: $name") unless ($id > 0);
    fatal("failed to remove key: $name") if (delete_key($id) < 0);
    print "Key successfully deleted: $name (id=$id)\n";
}


sub regenkeys($) {
  my($args) = @_;
  my($server,$type) = split(/,/,$args);

  $server=getserver($server);
  $type=gettype($type);

  my @keys;
  db_query("SELECT id,name,algorithm,keysize FROM keys " .
	   "WHERE type=1 AND ref=$server AND mode=0",\@keys);
  fatal("No keys found to regenerate") unless (@keys > 0);


  my $i;
  for $i (0..$#keys) {
    my($id,$name,$algo,$len) = @{$keys[$i]};

    print "Generating key: $name ...\n";
    my $okey = generate_key($name,$type,$len,$algo);
    my $raw = decode_base64($okey);
    my $newlen = length($raw) * 8;
    my $key=encode_base64(tsig_secret_encrypt($SAURON_KEY,$raw),"");
    chomp($key);
    print "Key: $okey  Encrypted-Key: $key\n" if ($opt_verbose);

    fatal("Failed to update key: $name")
      if (update_key({id=>$id,secretkey=>$key,keysize=>$newlen}) < 0);
  }

}

# eof :-)

