#!/usr/bin/perl -I/opt/sauron
#
# last -- utlity to display lastlog info
#
# Copyright (c) Michal Kostenec <kostenec@civ.zcu.cz> 2013-2014.
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2001-2003.
# $Id:$
#
require 5;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::BackEnd;
use Sauron::Sauron;
use Sauron::SetupIO;
use Text::Table;

set_encoding();
load_config();

##############################################

if (($ARGV[0] =~ /^--?h/)) {
  print "syntax: $0 [-h] [-num] [name]\n\n";
  exit(0);
}

if ($ARGV[0] =~ /^-(\d+)/) {
  $count_rule="$1";
  shift;
}

$user_rule="$ARGV[0]" if ($ARGV[0]);

db_connect();

$count=get_lastlog($count_rule,$user_rule,\@q);

# init table
my $tb = Text::Table->new('User', 'SID', 'Host', 'Login', 'Logout');

for $j (0..($count-1)) {
  $tb->add($q[$j][0],$q[$j][1],$q[$j][2],$q[$j][3],$q[$j][4]);
}

# print table
print $tb->title();
print $tb->body_rule('-');
print $tb->body();

exit 0;

