#!/usr/bin/perl
#
# runsql - utility to run SQL code from files given as parameters
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2001.
# $Id$
#
require 5;
use Getopt::Long;
use Term::ReadKey;


my ($PG_DIR,$PG_NAME) = ($0 =~ /^(.*\/)(.*)$/);
$0 = $PG_NAME;

do "$PG_DIR/config" || die("cannot load config");
do "$PG_DIR/util.pl";
do "$PG_DIR/db.pl";

sub fatal($) {
  my ($msg) = @_;
  print STDERR "$0: $msg\n";
  exit(1);
}

sub error($) {
  my ($msg) = @_;
  print STDERR "$0: $msg\n";
}

##############################################

$result = GetOptions("help|h","verbose|v","notransaction|n");

$count=@ARGV;

if ($opt_help || $count < 1) {
  print "syntax: $0 [--help] [--separate] <filename> [<filename> ...]\n\n";
  print " Parameter descriptions: \n",
        "   --notransaction  do not use transactions\n",
        "   --verbose        display SQL code\n",
        "\n";
  exit(0);
}

db_connect();
db_debug(0);

$verbose=1 if ($opt_verbose);

db_begin() unless ($opt_notransaction);

while ($filename=$ARGV[0]) {
  shift;
  unless (open(FILE,$filename)) {
    error("cannot open file: $filename");
    next;
  }
  print "Processing file: $filename\n" if ($verbose);
  $comment=0;
  $cmd='';
  
  while(<FILE>) {
  fileloop:
    s/\s*$//;
    s/\/\*.*\*\///;
    if (/(\/\*.*$)/) {
      #print "comment start: '$1'\n";
      $comment=1;
      s/\/\*.*$//;
    } elsif (/(^.*\*\/)/) {
      #print "comment end: '$1'\n";
      $comment=0;
      s/^.*\*\///;
    } elsif ($comment) { 
      next; 
    }
    next if (/^\s*$/);

    if (/(^.*?;)/) {
      $last=$1;
      $cmd .= $last;
      $cmd =~ s/^\s+//;
      unless ($cmd =~ /^\s*$/) {
	print "command: '$cmd'\n" if ($verbose);
	$res = db_exec($cmd);
	if ($res < 0) {
	  error("SQL command failed at $filename($.)");
	  exit(1) unless($opt_notransaction);
	}
      }
      $cmd='';
      s/(^.*?;)//;
      goto fileloop;
    }	

    #print "   $_\n" if ($verbose);
    s/\s+/ /g;
    $cmd .= $_;
  }

  close(FILE);
}

unless ($opt_notransaction) {
  fatal("cannot changes to database!") if (db_commit() < 0);
}

exit;

