#!/usr/bin/perl -I/usr/local/sauron
#
# status -- utlity to query/modify system status
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2001.
# $Id$
#
require 5;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::BackEnd;

my ($PG_DIR,$PG_NAME) = ($0 =~ /^(.*\/)(.*)$/);
$0 = $PG_NAME;

if (-r "/etc/sauron/config") {
  $config_file="/etc/sauron/config";
} elsif (-r "/usr/local/etc/sauron/config") {
  $config_file="/usr/local/etc/sauron/config"; 
} else {
  die("cannot find config file in /etc/sauron or /usr/local/etc/sauron");
}

do "$config_file" || die("cannot load config: $config_file");

##############################################

$argcount=@ARGV;

$result = GetOptions("cgi-enable","cgi-disable=s","help|h","pending:s",
		     "quiet");

if ($opt_help || not $result) {
  print "syntax: $0 [options]\n\n",
    "options:\n",
    " --help                       display this help\n",
    " --pending                    display number of hosts pending\n",
    " --pending=<servername>       display pending hosts for a server\n\n",
    " --cgi-disable='message'      disable CGI interface\n",
    " --cgi-enable                 enable CGI interface\n",
    " --quiet                      no verbose output\n";
  exit(0);
}

fatal("DB_CONNECT not defined in configuration!") unless ($DB_CONNECT);
$db_ok = db_connect2($DB_CONNECT);

$VER=sauron_version();
$DBVER=sauron_db_version();
$dbversion=get_db_version();

if ($argcount < 1 && (! $opt_quiet)) {
  print "Sauron v$VER status\n\n";
  printf "Database connection:   %s\n", ($db_ok?"OK":"ERROR");
  exit unless ($db_ok);
  printf "Database version:      %s\t%s\n", $dbversion,
    ($dbversion < $DBVER ? "Database version too old ($DBVER required)!":'');
}

exit unless ($db_ok);

if (defined $opt_pending) {
  unless ($opt_pending) {
    unless ($opt_quiet) {
      print "Pending host record modifications:\n\n",
	    "Server                                             Hosts\n",
	    "------------------------------------------------   -----\n";
    }
    get_server_list(-1,\%servers_h,\@servers);
    for $i (0..$#servers) {
      $serverid=$servers[$i];
      next if ($serverid < 0);
      $server=$servers_h{$serverid};

      undef @q;
      db_query("SELECT COUNT(h.id) FROM hosts h, zones z " .
	       "WHERE z.server=$serverid AND h.zone=z.id " .
	       " AND (h.mdate > z.serial_date OR h.cdate > z.serial_date);",
	       \@q);
      next if ($opt_quiet && $q[0][0] < 1);
      printf "%-50s %d\n",substr($server,0,50),$q[0][0];
    }
    exit;
  }

  $serverid=get_server_id($opt_pending);
  fatal("cannot find server '$opt_pending'") unless ($serverid > 0);
  print "Pending host modifications for server: $opt_pending (id=$serverid)\n"
    unless ($opt_quiet);

  $zones=get_zone_list($serverid,'M','f');
  for $i (0..$#{$zones}) {
    $zoneid=$$zones[$i][1];
    undef @q;
    db_query("SELECT h.domain,h.cdate,h.mdate,h.cuser,h.muser " .
	     "FROM hosts h, zones z " .
	     "WHERE z.id=$zoneid AND h.zone=z.id " .
	     " AND (h.mdate > z.serial_date OR h.cdate > z.serial_date) " .
	     "ORDER BY h.domain;",\@q);
    $count=@q;
    next unless ($count > 0);
    print "Zone: $$zones[$i][0] ($count)\n";
    for $j (0..$#q) {
      if ($q[$j][1] > $q[$j][2]) { 
	$date=localtime($q[$j][1]); $user=$q[$j][3]; $mode='Create';
      } else {
	$date=localtime($q[$j][2]); $user=$q[$j][4]; $mode='Modify';
      }
      printf "%-30s %6s  %-20s  %s\n",$q[$j][0],$mode,$date,$user;
    }
  }

  exit;
}



if (defined $opt_cgi_enable) {
  db_exec("DELETE FROM settings WHERE key='cgi_disable';");
  undef @q;
  db_query("SELECT value FROM settings WHERE key='cgi_disable';",\@q);
  if (@q > 0) {
    print STDERR "Cannot enable CGI interface!\n";
    exit(1);
  }
  print "CGI interface successfully enabled\n";
  exit;
}

if ($opt_cgi_disable) {
  $msg=$opt_cgi_disable;
  if ($msg =~ /^\s*$/) {
    print "CGI disable requires message\n";
    exit;
  }
  $msg=db_encode_str($msg);
  undef @q;
  db_query("SELECT value FROM settings WHERE key='cgi_disable';",\@q);
  if (@q > 0) {
    $res=db_exec("UPDATE settings SET value='$msg' WHERE key='cgi_disable';");
  } else {
    $res=db_exec("INSERT INTO settings (key,value) " .
		 "VALUES('cgi_disable',$msg);");
  }
  print "CGI interface successfully disabled.\n";
  exit;
}


undef @q;
db_query("SELECT value FROM settings WHERE key='cgi_disable';",\@q);

unless ($opt_quiet) {
  printf "CGI interface:         %s\n",
    ($q[0][0] ne '' ? "Disabled ($q[0][0])":"Enabled");

  print "\n";
}


$USER_TIMEOUT=3600 unless ($USER_TIMEOUT > 0);
$timeout=$USER_TIMEOUT;

get_who_list(\@who,$timeout);

if (@who > 0) {
  printf("%-8s %-22s %-15s %-6s %s\n",'USER','NAME','FROM','IDLE','LOGIN')
    unless ($opt_quiet);

  for $i(0..$#who) {
    printf("%-8s %-22s %-15s %-6s %s\n",
	   $who[$i][0],$who[$i][1],$who[$i][2],$who[$i][3],$who[$i][4]);
  }
} else {
  print "No users currently logged in.\n";
}

print "\n";
exit(0);

# eof


