#!/usr/bin/env bash
# docker-entrypoint.sh — configure Sauron from env, init DB if empty, start Apache
set -euo pipefail

SAURON_HOME="${SAURON_HOME:-/usr/local/sauron}"
SAURON_ETC="${SAURON_ETC:-/usr/local/etc/sauron}"
export PERL5LIB="${PERL5LIB:-$SAURON_HOME}"
export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"

# --- defaults (must match docker-compose.yml) --------------------------------
: "${SAURON_DB_HOST:=db}"
: "${SAURON_DB_PORT:=5432}"
: "${SAURON_DB_NAME:=sauron}"
: "${SAURON_DB_USER:=sauron}"
: "${SAURON_DB_PASSWORD:=sauron}"
: "${SAURON_ADMIN_USER:=admin}"
: "${SAURON_ADMIN_PASSWORD:=admin}"
: "${SAURON_ADMIN_EMAIL:=admin@example.com}"
: "${SAURON_ADMIN_NAME:=Sauron Admin}"
: "${SAURON_SERVER_ID:=docker}"
: "${SAURON_ENV_NAME:=DEV}"

export PGPASSWORD="$SAURON_DB_PASSWORD"
export PGHOST="$SAURON_DB_HOST"
export PGPORT="$SAURON_DB_PORT"
export PGUSER="$SAURON_DB_USER"
export PGDATABASE="$SAURON_DB_NAME"

log() { printf '%s %s\n' "[sauron-entrypoint]" "$*"; }

write_config() {
  local conf="$SAURON_ETC/config"
  local bconf="$SAURON_ETC/config-browser"
  local dsn="dbi:Pg:dbname=${SAURON_DB_NAME};host=${SAURON_DB_HOST};port=${SAURON_DB_PORT}"

  log "Writing $conf from environment"
  cat >"$conf" <<EOF
# Generated by docker-entrypoint.sh — do not edit in-container; set env vars instead.
\$PROG_DIR = "${SAURON_HOME}/";
\$LOG_DIR = "\$PROG_DIR/logs/";
\$SERVER_ID = "${SAURON_SERVER_ID}";

\$DB_DSN = "${dsn}";
\$DB_USER = "${SAURON_DB_USER}";
\$DB_PASSWORD = "${SAURON_DB_PASSWORD}";

\$SAURON_ICON_PATH = "/sauron/icons";
\$SAURON_CHARSET = 'utf-8';
\$SAURON_ENV_NAME = "${SAURON_ENV_NAME}";
\$SAURON_TOPMENU_BGCOLOR = "#0d6efd";

1;
EOF

  log "Writing $bconf from environment"
  cat >"$bconf" <<EOF
# Generated by docker-entrypoint.sh — browser.cgi config
\$PROG_DIR = "${SAURON_HOME}/";

\$DB_DSN = "${dsn}";
\$DB_USER = "${SAURON_DB_USER}";
\$DB_PASSWORD = "${SAURON_DB_PASSWORD}";

\$BROWSER_CHARSET = 'utf-8';

# No zones exposed until configured via web UI / CLI
\$BROWSER_CONF = {};

1;
EOF

  chmod 644 "$conf" "$bconf"
}

wait_for_db() {
  local i
  log "Waiting for PostgreSQL at ${SAURON_DB_HOST}:${SAURON_DB_PORT}..."
  for i in $(seq 1 60); do
    if pg_isready -h "$SAURON_DB_HOST" -p "$SAURON_DB_PORT" -U "$SAURON_DB_USER" -d "$SAURON_DB_NAME" >/dev/null 2>&1; then
      log "PostgreSQL is ready"
      return 0
    fi
    sleep 2
  done
  log "ERROR: PostgreSQL not ready after timeout"
  return 1
}

db_is_initialized() {
  # Probe for schema created by createtables (settings.dbversion).
  local out
  out="$(psql -v ON_ERROR_STOP=0 -At -c "SELECT value FROM settings WHERE setting='dbversion' LIMIT 1;" 2>/dev/null || true)"
  if [ -n "$out" ]; then
    return 0
  fi
  return 1
}

init_db() {
  log "Initializing empty Sauron database (createtables + seed + admin)"

  if [ ! -x "$SAURON_HOME/createtables" ]; then
    log "ERROR: $SAURON_HOME/createtables not found or not executable"
    return 1
  fi
  # createtables prompts [y/n]
  if ! printf 'y\n' | "$SAURON_HOME/createtables"; then
    log "ERROR: createtables failed"
    return 1
  fi

  if [ -r "$SAURON_HOME/contrib/named.root" ]; then
    log "Importing root hints"
    "$SAURON_HOME/import-roots" default "$SAURON_HOME/contrib/named.root" || log "WARN: import-roots failed"
  else
    log "WARN: contrib/named.root missing; skipping import-roots"
  fi

  if [ -r "$SAURON_HOME/contrib/Ethernet.txt" ]; then
    log "Importing OUI (Ethernet.txt)"
    "$SAURON_HOME/import-ethers" "$SAURON_HOME/contrib/Ethernet.txt" || log "WARN: import-ethers failed"
  fi
  if [ -r "$SAURON_HOME/contrib/additional-ether-codes.txt" ]; then
    "$SAURON_HOME/import-ethers" --force "$SAURON_HOME/contrib/additional-ether-codes.txt" || log "WARN: import-ethers --force failed"
  fi

  log "Creating superuser '${SAURON_ADMIN_USER}'"
  # adduser ends with exit(db_commit()); DBI true is 1, so success often
  # yields exit status 1 — do not treat that as failure under set -e.
  "$SAURON_HOME/adduser" \
    --user="$SAURON_ADMIN_USER" \
    --passwd="$SAURON_ADMIN_PASSWORD" \
    --name="$SAURON_ADMIN_NAME" \
    --email="$SAURON_ADMIN_EMAIL" \
    --comment="docker init" \
    --superuser ||
    true
  if [ -z "$(psql -At -c "SELECT 1 FROM users WHERE username='${SAURON_ADMIN_USER}' LIMIT 1;" 2>/dev/null || true)" ]; then
    log "ERROR: admin user '${SAURON_ADMIN_USER}' was not created"
    return 1
  fi

  log "Database initialization complete"
  if [ -x "$SAURON_HOME/status" ]; then
    "$SAURON_HOME/status" || true
  fi
}

start_apache() {
  log "Starting Apache (foreground)"
  # apache2ctl loads /etc/apache2/envvars itself; avoid sourcing under
  # `set -u` (envvars references unset APACHE_* vars with defaults).
  exec /usr/sbin/apache2ctl -D FOREGROUND
}

# --- main ---------------------------------------------------------------------
write_config
wait_for_db

if db_is_initialized; then
  log "Database already initialized (settings.dbversion present); skipping init"
else
  init_db || exit 1
fi

# Allow custom command (e.g. compose run sauron ./status)
if [ "$#" -gt 0 ] && [ "$1" != "apache2" ] && [ "$1" != "apachectl" ]; then
  log "Executing: $*"
  exec "$@"
fi

start_apache
