/* drop_tables.sql
 *
 * $Id:$
 */

DROP TABLE a_entries;
DROP TABLE acls;
DROP TABLE arec_entries;
DROP TABLE cidr_entries;
DROP TABLE common_fields;
DROP TABLE deleted_hosts;
DROP TABLE dhcp_entries;
DROP TABLE ds_entries;
DROP TABLE ether_info;
DROP TABLE group_entries;
DROP TABLE groups;
DROP TABLE hinfo_templates;
DROP TABLE history;
DROP TABLE hosts;
DROP TABLE keys;
DROP TABLE lastlog;
DROP TABLE leases;
DROP TABLE mx_entries;
DROP TABLE mx_templates;
DROP TABLE nets;
DROP TABLE news;
DROP TABLE ns_entries;
DROP TABLE printer_classes;
DROP TABLE printer_entries;
DROP TABLE root_servers;
DROP TABLE servers;
DROP TABLE settings;
DROP TABLE srv_entries;
DROP TABLE sshfp_entries;
DROP TABLE tlsa_entries;
DROP TABLE txt_entries;
DROP TABLE user_groups;
DROP TABLE user_rights;
DROP TABLE users;
DROP TABLE utmp;
DROP TABLE vlans;
DROP TABLE vmps;
DROP TABLE wks_entries;
DROP TABLE wks_templates;
DROP TABLE zones;

DROP SEQUENCE a_entries_id_seq;
DROP SEQUENCE acls_id_seq;
DROP SEQUENCE arec_entries_id_seq;
DROP SEQUENCE cidr_entries_id_seq;
DROP SEQUENCE dhcp_entries_id_seq;
DROP SEQUENCE ds_entries_id_seq;
DROP SEQUENCE group_entries_id_seq;
DROP SEQUENCE groups_id_seq;
DROP SEQUENCE hinfo_templates_id_seq;
DROP SEQUENCE history_id_seq;
DROP SEQUENCE hosts_id_seq;
DROP SEQUENCE keys_id_seq;
DROP SEQUENCE lastlog_id_seq;
DROP SEQUENCE leases_id_seq;
DROP SEQUENCE mx_entries_id_seq;
DROP SEQUENCE mx_templates_id_seq;
DROP SEQUENCE nets_id_seq;
DROP SEQUENCE news_id_seq;
DROP SEQUENCE ns_entries_id_seq;
DROP SEQUENCE printer_classes_id_seq;
DROP SEQUENCE printer_entries_id_seq;
DROP SEQUENCE root_servers_id_seq;
DROP SEQUENCE servers_id_seq;
DROP SEQUENCE sid_seq;
DROP SEQUENCE srv_entries_id_seq;
DROP SEQUENCE sshfp_entries_id_seq;
DROP SEQUENCE tlsa_entries_id_seq;
DROP SEQUENCE txt_entries_id_seq;
DROP SEQUENCE user_groups_id_seq;
DROP SEQUENCE user_rights_id_seq;
DROP SEQUENCE users_id_seq;
DROP SEQUENCE vlans_id_seq;
DROP SEQUENCE vmps_id_seq;
DROP SEQUENCE wks_entries_id_seq;
DROP SEQUENCE wks_templates_id_seq;
DROP SEQUENCE zones_id_seq;

/* eof */
